import type { Metadata } from 'next';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import DevHeader from '@/components/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko-KR'>
      <body className='font-sans'>
        <div className='w-full mx-auto font-sans max-w-7xl'>
          <DevHeader />
          <main className='px-2'>{children}</main>
        </div>
        <ToastContainer position='top-center' autoClose={2000} hideProgressBar closeOnClick pauseOnHover draggable />
      </body>
    </html>
  );
}
